services:
  - type: web
    name: whatsapp-api
    env: node
    plan: starter
    buildCommand: |
      npm ci
      npx playwright install
      echo "Playwright installation completed"
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    disk:
      name: playwright-cache
      mountPath: /opt/render/.cache
      sizeGB: 2
