services:
  - type: web
    name: your-service-name
    env: node
    plan: free
    buildCommand: |
      npm install
      npx playwright install --with-deps
    startCommand: npm start
    branch: master  # or your deployment branch
    autoDeploy: true
